baseURL = "http://github.center/"
languageCode = "en-us"
title = "The Center of Github"
theme="osprey"

canonifyURLS = true
googleAnalytics = ""
disqusShortname = "michaelflops"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Open source music for emotional people"
    author = "Michael Betts"
    description = "Full-stack web developer and UI/UX enthusiast based in Santa Cruz, CA."
    logoBig = "/images/github.png"
    logoSmall = "/images/github.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/github.png"
    twitter = ""
    linkedin = "michaelflops"
    github = "michaelflops"
    email = "michaelflops@gmail.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
